name: NeuralClear CI
on: [push]
jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: pip install --upgrade pip
      - name: Python Demo
        run: python neuralclear/neuralclear.py
      - name: Network Simulation
        run: python simulation.py

  rust-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
      - name: Check Rust
        run: |
          source "$HOME/.cargo/env"
          cargo --version
