name: NeuralClear CI
on: [push]
jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Python Demo
        run: python neuralclear/neuralclear.py
      - name: Network Simulation
        run: python simulation.py
  rust-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-rust@v2
      - name: Rust Build
        run: cargo check
